version: '2'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - keycloak:kc
    depends_on:
      - keycloak
  keycloak:
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    container_name: keycloak
    image: jboss/keycloak:13.0.1
    expose:
      - 8080
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
