version: '2'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    links:
      - keycloak:kc
    depends_on:
      - keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:13.0.1
    volumes:
      - .:/keycloak
    expose:
      - 8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
